version: '3.8'

services:
  mysqldb:
    container_name: mysqldb-container
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend

  server-api:
    container_name: server-api-container
    depends_on:
      - mysqldb
    build: 
      context: ./server-api
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 8081:8080
    volumes:
      - ./server-api:/usr/src/app
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
    networks:
      - backend
      - frontend

  server-ui:
    container_name: server-ui-container
    depends_on:
      - server-api
    build:
      context: ./server-ui
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
    ports:
      - 3000:3000
    volumes:
      - ./server-api:/usr/src/app
    networks:
      - frontend  


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - server-api
      - server-ui

volumes: 
  db:

networks:
  backend:
  frontend:
